const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'dessert',
    price: 15.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSYnOyHI1xBzO8utCodau_2n_N-69EE6dZmZNif5gW3thJdcBf1OH1BeVG5QaKYvGvOPY&usqp=CAU",
    desc: "Enjoy our lovely and fluffy self-made pancakes with strawberries and blueberries. The perfect dessert.",
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 19.99,
    img: "https://cdn.pixabay.com/photo/2020/03/21/11/17/burger-4953465__340.jpg",
    desc: `3 Burgers for 2 people. Juicy beef, fresh tomatoes and salad make this the perfect burger.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://img.ccnull.de/1015000/preview/1016180_86ca754787687fbe2ea1d48f681337bf.jpg',
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur quo quidem deleniti explicabo, est molestias." ,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Breakfast_in_Australia%3B_bacon_and_fried_eggs_on_toast.jpg',
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, fuga voluptate tempora omnis dicta necessitatibus eaque obcaecati.",
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://cdn.pixabay.com/photo/2019/01/16/12/15/spaghetti-3935839_1280.jpg',
    desc: "Ipsum error ad consectetur laborum modi provident nobis ducimus ut culpa ea odit, quae repudiandae non id esse corrupti iste optio sit!",
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Oreo_Milkshake.JPG',
    desc: "Atque rem similique enim ullam, quas perferendis nemo totam? Dignissimos ab at id labore amet ratione libero ipsam neque esse? Tempore, fugiat.",
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Bacon%2C_egg%2C_and_cheese_on_bread.jpg',
    desc: "Sapiente, quo velit ab temporibus dolorem eaque non dolor consequatur dolore corporis tempora, maxime ut molestiae ducimus excepturi laboriosam aliquam quas commodi.",
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 15.99,
    img: 'https://www.tft-mag.com/wp-content/uploads/2017/05/Business-Lunch-In-Hamburg-Restaurant-Image-13586-1100x650.jpg',
    desc: "Vero nisi in a dicta ut officiis, deleniti quam quasi, eligendi molestiae autem voluptas esse accusamus, reiciendis magni. Praesentium quam deleniti dignissimos?",
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://cdn.pixabay.com/photo/2016/05/26/19/49/strawberry-smoothie-1418212_1280.jpg',
    desc: "Asperiores quam doloribus molestiae ab aliquam quo repellendus a in dolore vitae. Minima dolore nisi dolor quidem, corporis modi quibusdam sed repellendus?",
  },
    {
    id: 10,
    title: 'pizza classico',
    category: 'lunch',
    price: 23.99,
    img: 'https://live.staticflickr.com/5471/10522215603_2604706a1d_b.jpg',
    desc: "Maiores repellendus quia quidem? Nulla adipisci aliquam quidem, eveniet sapiente, quos dignissimos ea accusamus velit eligendi quo quisquam! Atque illum tempora itaque!",
  },
];
export default menu;